INSERT INTO CATEGORIA (nome) VALUES
	 ('MERCADINHO'),
	 ('ATACAREJO'),
	 ('PADARIA'),
	 ('ARMAZEM CONSTRUÇÃO'),
	 ('FARMACIA'),
	 ('DEPARTAMENTOS'),
	 ('CALÇADOS'),
	 ('E-COMMERCE'),
	 ('INFORMATICA'),
	 ('POSTOS COMBUSTIVEIS');
INSERT INTO CATEGORIA (nome) VALUES
	 ('ESTACIONAMENTO '),
	 ('ASSINATURA'),
	 ('RESTAURANTE'),
	 ('VENDA DE GAS'),
	 ('VENDA DE OXIGENIO'),
	 ('AGUA E ESGOTO'),
	 ('ENERGIA ELETRICA'),
	 ('OFICINA MERCANICA'),
	 ('MANICURE'),
	 ('BOLTIQUE');
INSERT INTO CATEGORIA (nome) VALUES
	 ('CLOUD ARMAZENAGEM'),
	 ('SUPERMERCADOS'),
	 ('MOVEIS E ELETRO'),
	 ('AUTO PEÇAS'),
	 ('VARIEDADES'),
	 ('FERRAMENTAS');
