INSERT INTO ESTABELECIMENTO (nome) VALUES
	 ('BOA OPÇÃO'),
	 ('PANIF FLOR IBURA'),
	 ('FERREIRA COSTA'),
	 ('ATACADO DOS PRESENTES'),
	 ('FARM PAGUEMENOS'),
	 ('FARM PERMANENTE'),
	 ('FARM IRIS'),
	 ('MARISA'),
	 ('TORRA TORRA'),
	 ('RIACHOELO');
INSERT INTO ESTABELECIMENTO (nome) VALUES
	 ('C&A'),
	 ('ESPOSENDE '),
	 ('FIGUEIRA CALÇADOS'),
	 ('DISANTINI'),
	 ('MERCADO LIVRE'),
	 ('OLX'),
	 ('KABUM'),
	 ('SHEIN'),
	 ('AMAZON'),
	 ('SHOPEE');
INSERT INTO ESTABELECIMENTO (nome) VALUES
	 ('TEMU'),
	 ('LOGNET INFORMATICA'),
	 ('POSTO SHELL'),
	 ('ZAE-RECIFE'),
	 ('PRIME AMAZON'),
	 ('NETFLIX'),
	 ('UDEMY CURSOS'),
	 ('GOOGLE ONE'),
	 ('ATLANTICO PIZZARIA'),
	 ('REST FIDALGO');
INSERT INTO ESTABELECIMENTO (nome) VALUES
	 ('ARRUMADINHO SAM'),
	 ('MIX MATEUS'),
	 ('ATACADÃO'),
	 ('DESKONTÃO'),
	 ('AÇAI ATACADISTA'),
	 ('MJ CONSTRUÇÃO'),
	 ('JS CONSTRUÇÃO'),
	 ('HOBBY CONSTRUÇÃO'),
	 ('VITÓRIA GAS'),
	 ('MOISES GAS');
INSERT INTO ESTABELECIMENTO (nome) VALUES
	 ('GASIL OXIGENIO'),
	 ('OXIL OXIGENIO'),
	 ('COMPESA'),
	 ('NEO ENERGIA'),
	 ('AUTOPEÇAS MARINGA'),
	 ('TRADIÇÃO MOVEIS'),
	 ('ELETROSHOPPING'),
	 ('CASAS BAHIA'),
	 ('MAGAZINE LUIZA'),
	 ('DCHIC MODAS');
INSERT INTO ESTABELECIMENTO (nome) VALUES
	 ('CARREFOUR'),
	 ('CRISTINA DESGN'),
	 ('MARRON ALINHAMENTO'),
	 ('PALMA FERRAMENTAS');
