INSERT INTO LOCAL_COMPRA (nome) VALUES
	 ('CONDE DA BOA VISTA'),
	 ('LOTEAMENTO'),
	 ('SHOPPING CENTER RECIFE'),
	 ('SHOPPING CENTER RIO MAR'),
	 ('AVENIDA DOIS RIOS'),
	 ('MASCARENHAS DE MORAES'),
	 ('RUA DA PALMA'),
	 ('INTERNET'),
	 ('SEM LOCAL'),
	 ('AVENIDA SANTA FÉ');
INSERT INTO LOCAL_COMPRA (nome) VALUES
	 ('AVENIDA JEAN EMILE FRAVE'),
	 ('AVENIDA SAPUCAIA');
