INSERT INTO PRODUTO (nome) VALUES
	 ('FEIRA PARCIAL'),
	 ('FEIRA  COMPLETA'),
	 ('PÃO'),
	 ('LACTICINEOS '),
	 ('ARTIGO PARA CASA'),
	 ('ARTIGO PARA CONSTRUÇÃO'),
	 ('ARTIGO PARA MARCENARIA'),
	 ('ARTIGO PARA OFICINA'),
	 ('ARTIGO PARA ELETRICAS'),
     ('ARTIGO PARA COZINHA'),
	 ('ARTIGO PARA QUARTOS'),
	 ('ARTIGO PARA SALA'),
     ('ARTIGO FEMININO'),
	 ('ARTIGO MASCULINO'),
     ('ARTIGO PARA SERRALHARIA');
INSERT INTO PRODUTO (nome) VALUES
	 ('SOVERTE E CHOCOLATE'),
	 ('CALÇADOS'),
	 ('BOLÇAS'),
	 ('MEDICAMENTOS PGOV'),
	 ('MEDICAMENTOS  USO GERAL'),
	 ('ENTRETENDIMENTO'),
	 ('ALMOÇO');
INSERT INTO PRODUTO (nome) VALUES
	 ('LANCHE'),
	 ('PELICULA CELULAR'),
	 ('BEBIDAS ALCOLICAS'),
	 ('FERRAMENTAS USO GERAL'),
	 ('FERRAMENTAS AUTOMATIVAS'),
	 ('FERRAMENTAS P/CONSTRUÇÃO'),
	 ('TUBO Q-20X20'),
	 ('TUBO Q40X40');
INSERT INTO PRODUTO (nome) VALUES
	 ('BIJOUTERIA'),
	 ('FOGÃO'),
	 ('SOFA'),
	 ('MOVEIS DE COZINHA'),
	 ('ALINHAMENTO E BALACEAMENTO'),
	 ('OXIGENIO'),
	 ('ACENTILENO'),
	 ('PEÇAS PARA PC'),
	 ('PEÇAS PARA FUNELARIA')
     ('PEÇAS AUTOMOTIVAS');